Update dependencies
Critical dependencies:
* Google Mobile Vision to 20.1.3
* Commons Imaging to 1.0-alpha2

Build related:
* Gradle to 6.7.1
* Android gradle plugin to 4.2.2
* Kotlin to 1.5.20

Could not update robolectric to 4.6.1 due to some tests failing with:
```
java.lang.IllegalAccessException: Class androidx.test.espresso.base.ThreadPoolExecutorExtractor$2
can not access a member of class androidx.loader.content.ModernAsyncTask with
modifiers "public static final"
```